vpcname             = "google_demo_project_vpc"
cidr                = "10.0.0.0/16"
az                  = ["us-east-1a", "us-east-1b"]
public_subnet_cidr  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidr = ["10.0.3.0/24", "10.0.4.0/24"]
sgname              = "google_project_albsg"
clustername         = "google_project_cluster"
node_instance_type  = "c7i-flex.large"
region              = "us-east-1"
albname             = "googleproject"
